name: CI/CD - FCG
  
on:
  push:
    branches-ignore:
      - master  # push direto na master NÃO dispara o pipeline
  pull_request:
    branches:
      - master  # master dispara SÓ por PR

jobs:
  build-test-pushDockerImage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore FCG.FiapCloudGames.sln

      - name: Build
        run: dotnet build FCG.FiapCloudGames.sln --configuration Release --no-restore

      - name: Unit Tests with Coverage
        run: dotnet test FCG.FiapCloudGames.sln --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"
        
      - name: Login to Azure Container Registry
        run: echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login acrfcg.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t acrfcg.azurecr.io/fiapcloudgames/api:latest .

      - name: Push Docker image to ACR
        run: docker push acrfcg.azurecr.io/fiapcloudgames/api:latest

  deploy-dev:
    needs: build-test-pushDockerImage
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container App - DEV
        run: |
          az containerapp update \
            --name aca-fcg-dev \
            --resource-group RG_FCG \
            --image acrfcg.azurecr.io/fiapcloudgames/api:latest \
            --set-env-vars \
                "FiapCloudGamesDbConnection=${{ secrets.FCG_DB_CONNECTION_STRING }}" \
                "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
                "NEW_RELIC_APP_NAME=${{ vars.NEW_RELIC_APP_NAME }}" \
                "ASPNETCORE_ENVIRONMENT=${{ vars.ENV }}"

  deploy-uat:
    needs: deploy-dev
    runs-on: ubuntu-latest
    environment: UAT

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container App - UAT
        run: |
          az containerapp update \
            --name aca-fcg-uat \
            --resource-group RG_FCG \
            --image acrfcg.azurecr.io/fiapcloudgames/api:latest \
            --set-env-vars \
                "FiapCloudGamesDbConnection=${{ secrets.FCG_DB_CONNECTION_STRING }}" \
                "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
                "NEW_RELIC_APP_NAME=${{ vars.NEW_RELIC_APP_NAME }}" \
                "ASPNETCORE_ENVIRONMENT=${{ vars.ENV }}"

  deploy-prd:
    needs: deploy-uat
    runs-on: ubuntu-latest
    environment: PRD
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Container App - PRD
        run: |
          az containerapp update \
            --name aca-fcg \
            --resource-group RG_FCG \
            --image acrfcg.azurecr.io/fiapcloudgames/api:latest \
            --set-env-vars \
                "FiapCloudGamesDbConnection=${{ secrets.FCG_DB_CONNECTION_STRING }}" \
                "NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
                "NEW_RELIC_APP_NAME=${{ vars.NEW_RELIC_APP_NAME }}" \
                "ASPNETCORE_ENVIRONMENT=${{ vars.ENV }}"

